version: '2'
services:
  default-website:
    image: flaccid/rancher-services-gateway
    stdin_open: true
    tty: true
    command:
    - /usr/local/rsg/bin/rsg
    - --ui
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label_soft: tier=private
  service-discovery:
    image: flaccid/rancher-services-gateway
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label_soft: tier=private
  router-tcp-80:
    image: jamessharp/docker-nginx-https-redirect
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label_soft: tier=private
  router-tcp-443:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.scheduler.affinity:host_label_soft: tier=private
      services_gateway: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  dns-updater:
    image: flaccid/ranch53
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      POLL_INTERVAL: '30'
{{- if (.Values.RANCHER_URL)}}
      RANCHER_URL: ${RANCHER_URL}
{{- end}}
{{- if (.Values.RANCHER_ACCESS_KEY)}}
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
{{- end}}
{{- if (.Values.RANCHER_SECRET_KEY)}}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
{{- end}}
{{- if (.Values.FORWARD_PROXY)}}
      http_proxy: ${FORWARD_PROXY}
{{- end}}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: tier=private
